"""Python bindings for Software Heritage graph access."""

from __future__ import annotations

from typing import Iterator

import enum

import numpy as np
import numpy.typing as npt

from webgraph import BvGraph

class PySuccessorsIterator:
    """Iterator over node IDs (successors or predecessors)."""

    def __iter__(self) -> PySuccessorsIterator: ...
    def __next__(self) -> int: ...

class PyNodeType(enum.IntEnum):
    """SWH node types.

    Integer values match the encoding used in the SWH graph:
    Content=0, Directory=1, Origin=2, Release=3, Revision=4, Snapshot=5.
    """

    Content = 0
    Directory = 1
    Origin = 2
    Release = 3
    Revision = 4
    Snapshot = 5

class SwhGraph:
    """A bidirectional Software Heritage graph with node properties.

    Loads the graph and all available properties (maps, persons, strings,
    timestamps) from the given base path.  Node IDs are integers in
    ``[0, num_nodes)``.
    """

    def __init__(self, path: str) -> None: ...
    @property
    def basepath(self) -> str: ...
    def num_nodes(self) -> int: ...
    def outdegree(self, node: int) -> int: ...
    def indegree(self, node: int) -> int: ...
    def predecessors(self, node: int) -> PySuccessorsIterator: ...
    def successors(self, node: int) -> PySuccessorsIterator: ...
    def committer_id(self, node: int) -> int | None: ...
    def author_id(self, node: int) -> int | None: ...
    def node_type(self, node: int) -> PyNodeType: ...
    def committer_timestamp(self, node: int) -> int | None: ...
    def author_timestamp(self, node: int) -> int | None: ...
    def swhid(self, node: int) -> str: ...
    def swh_link(self, node: int) -> str: ...
    def message(self, node: int) -> str | None: ...
    def tag_name(self, node: int) -> str | None: ...
    def outdegrees(self) -> npt.NDArray[np.uint32]: ...
    def indegrees(self) -> npt.NDArray[np.uint32]: ...
    def top_k_out(self, k: int) -> list[tuple[int, int]]: ...
    def top_k_in(self, k: int) -> list[tuple[int, int]]: ...
    def subgraph(self, node_types: str) -> FilteredSwhGraph: ...
    def forward_graph(self) -> BvGraph: ...
    def backward_graph(self) -> BvGraph: ...
    def __repr__(self) -> str: ...

class FilteredSwhGraph:
    """A view of an SwhGraph restricted to specific node types.

    Created by ``SwhGraph.subgraph()``.  Node IDs are not renumbered.
    """

    def num_nodes(self) -> int: ...
    def outdegree(self, node: int) -> int: ...
    def indegree(self, node: int) -> int: ...
    def successors(self, node: int) -> PySuccessorsIterator: ...
    def predecessors(self, node: int) -> PySuccessorsIterator: ...
    def outdegrees(self) -> npt.NDArray[np.uint32]: ...
    def indegrees(self) -> npt.NDArray[np.uint32]: ...
    def committer_id(self, node: int) -> int | None: ...
    def author_id(self, node: int) -> int | None: ...
    def node_type(self, node: int) -> PyNodeType: ...
    def committer_timestamp(self, node: int) -> int | None: ...
    def author_timestamp(self, node: int) -> int | None: ...
    def swhid(self, node: int) -> str: ...
    def swh_link(self, node: int) -> str: ...
    def message(self, node: int) -> str | None: ...
    def tag_name(self, node: int) -> str | None: ...
    def top_k_out(self, k: int) -> list[tuple[int, int]]: ...
    def top_k_in(self, k: int) -> list[tuple[int, int]]: ...
    def has_node(self, node: int) -> bool: ...
    def __repr__(self) -> str: ...

class ContributorNamesMap:
    """Sparse map from contributor IDs to display names."""

    def __init__(self, path: str) -> None: ...
    def get_name(self, contributor_id: int) -> str | None: ...
