"""Python bindings for the WebGraph compressed graph framework."""

from typing import Iterator

import numpy as np
import numpy.typing as npt

class PySuccessorsIterator:
    """Iterator over node IDs (successors or predecessors)."""

    def __iter__(self) -> PySuccessorsIterator: ...
    def __next__(self) -> int: ...

class PyBfsIterator:
    """Iterator for breadth-first traversal.

    Yields ``(root, parent, node, distance)`` tuples where *root*
    identifies the BFS tree, *parent* is the node from which *node*
    was discovered (equal to *node* for roots), and *distance* is the
    hop count from *root*.
    """

    def __iter__(self) -> PyBfsIterator: ...
    def __next__(self) -> tuple[int, int, int, int]: ...

class BvGraph:
    """A compressed graph in WebGraph format.

    Provides forward-only access (successors) and BFS traversal.
    For backward (predecessor) access, load the transposed graph.
    """

    def __init__(self, basename: str) -> None: ...
    def num_nodes(self) -> int: ...
    def num_arcs(self) -> int: ...
    def outdegree(self, node: int) -> int: ...
    def successors(self, node: int) -> PySuccessorsIterator: ...
    def outdegrees(self) -> npt.NDArray[np.uint32]: ...
    def top_k_out(self, k: int) -> list[tuple[int, int]]: ...
    def bfs(self) -> PyBfsIterator: ...
    def bfs_from_node(self, node: int) -> PyBfsIterator: ...
    def __repr__(self) -> str: ...
